language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database oh_crop;' -U postgres
services:
- postgresql
script:
- pip install flask_api
- pip install flask-sqlalchemy psycopg2 flask-migrate
- pytest
deploy:
  provider: heroku
  api_key:
    secure: g40jTfOKxk7M+91PavzIJnmBOXt3IyKYTMegvLLHXAYTC9lEkdTlYbGe2DgjZP+rf+4aS2BvAh73PZvbuRlYluAxubzvgrr9w1rviMNq8eujmHEDfgAXlhEG94hdIi7uFV5kWQmGCKrdSP0zmSaz7wN+9yOYXE4iPZYZW1G53KDI43TxQmbWSrtS9lLJD9DXsw3OzuqbCZXhZ1Jj7G5mG9bIeS8oeTVJYhQss3PN+3LSn8kOQTjCHTYyLpUuET5w+Pij6PaAA5G7EnOsJxCcPeR5w005KKeTm+sAkMHve9YHOYcDIk5usMAlXWGmMNJQUWNUaUFjXVXoPIZ8YLqByDU+X4//V07o0XCgRJJJC9TgV2jaELhHG32Sey14lodclrvw/gLohJ0KnQjpK4U0tj9k9zDT8jx0v8SvjHH526nmJ4tuqbs7ADxcf4dh0d1IhEB6MQgKd8LPsJH415j97gQneAvQUrZWOrnENwq7dA9GmGYY+LJNabR2R48b0NLV4tzlSVrJ4TtEdx+lkYfEBJGrHizBbwjA26p72Vs81VtW0TdHxpaHtwkzQ1x0gaeKMKixOPkG8ttKfRGFsoZjN2SCRrACOyKtpVjlw4KpF7gEpGg/npBwqTAhgUylRERf/LBuwgjAlH0Rt9PJimJqGyyZuxKzaJzy5Ed1qM4WoHI=
  app: oh-crop-be
  on:
    branch: main
